apiVersion: v1
kind: Pod
metadata:
  labels:
    name: blog
  name: blog-pod
spec:
  containers:
  - name: git-sync
    image: gcr.io/google_containers/git-sync:v2.0.4
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: markdown
      mountPath: /git
    - name: git-secret
      mountPath: /etc/git-secret
    env:
    - name: GIT_SYNC_REPO
      value: git@github.com:Analect/test-sync.git
    - name: GIT_SYNC_DEST
      value: git
    - name: GIT_SYNC_SSH
      value: "true"
    - name: GIT_SYNC_WAIT
      value: "99999"
  - name: hugo
    image: gcr.io/google_containers/hugo
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: markdown
      mountPath: /src
    - name: html
      mountPath: /dest
    env:
    - name: HUGO_SRC
      value: /src/git/demo/blog
    - name: HUGO_BUILD_DRAFT
      value: "true"
    - name: HUGO_BASE_URL
      value: example.com
  - name: nginx
    image: nginx
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    - name: git-secret
      mountPath: /etc/git-secret
    ports:
    - containerPort: 80
  volumes:
  - name: markdown
    emptyDir: {}
  - name: html
    emptyDir: {}
  - name: git-secret
    secret:
      defaultMode: 256
      secretName: github-git-creds
